# Schema
name: box schema
type: map
mapping:
  tenant:
    type: str
    required: True
  defaults:
    type: map
    required: True
    mapping:
      availability_zone:
        required: True
        type: str
      flavor:
        required: True
        type: str
      image_name:
        required: True
        type: str
      internal_network_name:
        required: True
        type: str
      keypair:
        required: True
        type: str
      volumes:
        required: False
        type: map
        mapping:
          regex;(^volume\d):
            required: True
            type: map
            mapping:
              mount_point:
                type: str
                required: True
              size:
                type: str
                required: True
              volume_type:
                type: str
                required: True
  deploy:
    required: True
    type: map
    mapping:
      regex;():
        required: True
        type: map
        mapping:
          availability_zone:
            required: False
            type: str
          ip:
            required: False
            type: str
          flavor:
            required: True
            type: str
          image_name:
            required: True
            type: str
          internal_network_name:
            required: True
            type: str
          keypair:
            required: True
            type: str
          volumes:
            required: False
            type: map
            mapping:
              regex;(^volume\d):
                required: True
                type: map
                mapping:
                  mount_point:
                    required: True
                  size:
                    required: True
                  volume_type:
                    required: True







